In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('energydata_complete.csv')
df = df.drop(columns=['date', 'lights'])

In [3]:
df.head()

,Appliances,T1,RH_1,T2,RH_2,T3,RH_3,T4,RH_4,T5,...,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
0,60,19.89,47.596667,19.2,44.790000,19.79,44.730000,19.000000,45.566667,17.166667,...,17.033333,45.53,6.600000,733.5,92.0,7.000000,63.000000,5.3,13.275433,13.275433
1,60,19.89,46.693333,19.2,44.722500,19.79,44.790000,19.000000,45.992500,17.166667,...,17.066667,45.56,6.483333,733.6,92.0,6.666667,59.166667,5.2,18.606195,18.606195
2,50,19.89,46.300000,19.2,44.626667,19.79,44.933333,18.926667,45.890000,17.166667,...,17.000000,45.50,6.366667,733.7,92.0,6.333333,55.333333,5.1,28.642668,28.642668
3,50,19.89,46.066667,19.2,44.590000,19.79,45.000000,18.890000,45.723333,17.166667,...,17.000000,45.40,6.250000,733.8,92.0,6.000000,51.500000,5.0,45.410389,45.410389
4,60,19.89,46.333333,19.2,44.530000,19.79,45.000000,18.890000,45.530000,17.200000,...,17.000000,45.40,6.133333,733.9,92.0,5.666667,47.666667,4.9,10.084097,10.084097

In [4]:
#Normalize the dataset to common scale using min-max scaler
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
normalized_df = pd.DataFrame(scaler.fit_transform(df), columns=df.columns)
normalized_df.head()

C:\Users\user\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:334: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by MinMaxScaler.
  return self.partial_fit(X, y)

,Appliances,T1,RH_1,T2,RH_2,T3,RH_3,T4,RH_4,T5,...,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
0,0.046729,0.32735,0.566187,0.225345,0.684038,0.215188,0.746066,0.351351,0.764262,0.175506,...,0.223032,0.677290,0.372990,0.097674,0.894737,0.500000,0.953846,0.538462,0.265449,0.265449
1,0.046729,0.32735,0.541326,0.225345,0.682140,0.215188,0.748871,0.351351,0.782437,0.175506,...,0.226500,0.678532,0.369239,0.100000,0.894737,0.476190,0.894872,0.533937,0.372083,0.372083
2,0.037383,0.32735,0.530502,0.225345,0.679445,0.215188,0.755569,0.344745,0.778062,0.175506,...,0.219563,0.676049,0.365488,0.102326,0.894737,0.452381,0.835897,0.529412,0.572848,0.572848
3,0.037383,0.32735,0.524080,0.225345,0.678414,0.215188,0.758685,0.341441,0.770949,0.175506,...,0.219563,0.671909,0.361736,0.104651,0.894737,0.428571,0.776923,0.524887,0.908261,0.908261
4,0.046729,0.32735,0.531419,0.225345,0.676727,0.215188,0.758685,0.341441,0.762697,0.178691,...,0.219563,0.671909,0.357985,0.106977,0.894737,0.404762,0.717949,0.520362,0.201611,0.201611

In [8]:
target = normalized_df['Appliances']
features = normalized_df.drop(columns=['Appliances'])

In [12]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

linear_model = LinearRegression()

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(features,target, test_size=0.3, 
                                                   random_state=42)

In [22]:
#Question 12
linear_model.fit(X_train[['T2']], X_train.T6)
pred = linear_model.predict(X_test[['T2']])
#RSQUARED: R-Sqaured Score
rsquared = r2_score(y_test, pred)
print("R squared score: ", round(rsquared, 2))

R squared score:  -13.58

In [23]:
linear_model.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [25]:
predicted_values = linear_model.predict(X_test)

In [26]:
#Question 13
#MAE: Mean Absolute Error
mae = mean_absolute_error(y_test, predicted_values)
print("Mean Absolute Error (MAE): ", round(mae, 2))

Mean Absolute Error (MAE):  0.05

In [27]:
#Question 14
#RSS: Residual Sum of Squares
rss = np.sum(np.square(y_test - predicted_values))
print("Residual Sum of Squares (RSS): ", round(rss, 2))

Residual Sum of Squares (RSS):  45.35

In [28]:
#Question 15
#RMSE: Root Mean Squared Error
rmse = np.sqrt(mean_squared_error(y_test, predicted_values))
print("Root Mean Squared Error: ", round(rmse, 3))

Root Mean Squared Error:  0.088

In [29]:
#Question 16
#RSQUARED: R-Sqaured Score
rsquared = r2_score(y_test, predicted_values)
print("R squared score: ", round(rsquared, 2))

R squared score:  0.15

In [31]:
#Question 17
def get_weights_df(model, feat, col_name):
    weights =  pd.Series(model.coef_, feat.columns).sort_values()
    weights_df = pd.DataFrame(weights).reset_index()
    weights_df.columns = ['Features', col_name]
    weights_df[col_name].round(3)
    return weights_df
linear_weights_df = get_weights_df(linear_model, X_train, 'Linear_Model_Weight')
linear_weights_df

       Features  Linear_Model_Weight
0           rv2        -2.276510e+10
1          RH_2        -4.567150e-01
2         T_out        -3.218479e-01
3            T2        -2.361946e-01
4            T9        -1.899264e-01
5          RH_8        -1.576019e-01
6        RH_out        -7.765200e-02
7          RH_7        -4.458875e-02
8          RH_9        -3.981379e-02
9            T5        -1.566300e-02
10           T1        -3.281051e-03
11  Press_mm_hg         6.845979e-03
12           T7         1.031356e-02
13   Visibility         1.230399e-02
14         RH_5         1.600706e-02
15         RH_4         2.638924e-02
16           T4         2.899615e-02
17    Windspeed         2.919410e-02
18         RH_6         3.805687e-02
19         RH_3         9.603389e-02
20           T8         1.019936e-01
21    Tdewpoint         1.177425e-01
22           T6         2.364314e-01
23           T3         2.906326e-01
24         RH_1         5.535574e-01
25          rv1         2.276510e+10

In [32]:
#Question 18

#Ridge Regularization
from sklearn.linear_model import Ridge
ridge_reg = Ridge(alpha=.4)
ridge_reg.fit(X_train, y_train)
ridge_pred = ridge_reg.predict(X_test)
#Root Mean Square Error
from sklearn.metrics import mean_squared_error
rmse = np.sqrt(mean_squared_error(y_test, ridge_pred))
round(rmse, 3)

0.088

In [35]:
#Question 19

#LASSO Regularization
from sklearn.linear_model import Lasso
lasso_reg = Lasso(alpha=0.001)
lasso_reg.fit(X_train, y_train)
lasso_weights_df = get_weights_df(lasso_reg, X_train, 'Lasso_Model_Weight')
lasso_weights_df

       Features  Lasso_Model_Weight
0        RH_out           -0.049557
1          RH_8           -0.000110
2            T1            0.000000
3     Tdewpoint            0.000000
4    Visibility            0.000000
5   Press_mm_hg           -0.000000
6         T_out            0.000000
7          RH_9           -0.000000
8            T9           -0.000000
9            T8            0.000000
10         RH_7           -0.000000
11          rv1           -0.000000
12           T7           -0.000000
13           T6            0.000000
14         RH_5            0.000000
15           T5           -0.000000
16         RH_4            0.000000
17           T4           -0.000000
18         RH_3            0.000000
19           T3            0.000000
20         RH_2           -0.000000
21           T2            0.000000
22         RH_6           -0.000000
23          rv2           -0.000000
24    Windspeed            0.002912
25         RH_1            0.017880

In [37]:
#Question 20

#RMSE with the Lasso Regression
lasso_pred = lasso_reg.predict(X_test)
rmse = np.sqrt(mean_squared_error(y_test, lasso_pred))
round(rmse, 3)

0.094